In [1]:
import pickle
import numpy as np
import awkward as ak

In [2]:
filename = '../NeutrinoResults/nue_0-1_results.pickle'
with open(filename, 'rb') as f:
    data = pickle.load(f)

In [3]:
data

{'Ev': array([0.74536355, 0.50638228, 0.2596089 , ..., 0.27900875, 0.41083932,
        0.8209331 ]),
 'weight': array([0.00477819, 0.01109697, 0.044105  , ..., 0.03714184, 0.0179995 ,
        0.00379026]),
 'position': array([  4.26159355, 130.51052978,  62.90732498, ...,  10.34739151,
         77.46257714,  77.5602222 ]),
 'daughters': <Array [[[0.438, -0.00271, ..., 1], ...], ...] type='100000 * var * var * f...'>}

In [4]:
data['daughters']

<Array [[[0.438, -0.00271, ..., 1], ...], ...] type='100000 * var * var * f...'>

In [5]:
import sys
sys.path.insert(0,'../MomentumExtrapolation')
from Closest_Approach_Histogram import *

In [6]:
bool = get_reconstructable(data)

In [8]:
recon = ak.sum(bool, axis = 1) >= 1

In [13]:
reconstructed_3p = ak.fill_none(ak.mask(data['daughters'][:,:,1:4], bool),
                                    ak.Array([0,0,0]),axis = 1)

In [19]:
a = ak.sum(reconstructed_3p, axis = 1)

In [45]:
ak.sum(reconstructed_3p[recon], axis = 1).to_numpy()

array([[0.08275005, 0.07964472, 0.08275005],
       [0.23206389, 0.40939698, 0.23206389],
       [0.46593575, 0.04180243, 0.46593575],
       ...,
       [0.16771961, 0.13629011, 0.16771961],
       [0.22488873, 0.06252259, 0.22488873],
       [0.05786751, 0.16195396, 0.05786751]])

In [48]:
data['position'].reshape(len(data['weight']),3)

array([[  4.26159355, 130.51052978,  62.90732498],
       [ 25.3025939 ,  99.15226243,  69.59284812],
       [-46.26401819, 134.90003576,  60.89647165],
       ...,
       [ -6.2414028 ,  85.01875744,  66.94178162],
       [ 19.71319569, 127.87717771,  62.23017697],
       [ 10.34739151,  77.46257714,  77.5602222 ]])

In [49]:
data['position']

array([  4.26159355, 130.51052978,  62.90732498, ...,  10.34739151,
        77.46257714,  77.5602222 ])